### ISSUE TITLE
escript build breaks NIF load path

### ISSUE THREAD

**Issue by norbu09** [jazzyb/sqlite_ecto#23]
played around with this and noticed that in `iex` everything works nicely but if I build an `escript` out of the project I get the following error:

```
16:25:27.509 [error] The on_load function for module esqlite3_nif returned {{:badmatch,
  {:error,
   {:load_failed,
    'Failed to load NIF library: \'dlopen(priv/esqlite3_nif.so, 2): image not found\''}}},
 [{:esqlite3_nif, :init, 0, [file: 'src/esqlite3_nif.erl', line: 47]},
  {:code_server, :"-handle_on_load/4-fun-0-", 1,
   [file: 'code_server.erl', line: 1659]}]}
```

stack trace:

```
** (CaseClauseError) no case clause matching: {:undef, [{:esqlite3_nif, :start, [], []}, {:esqlite3, :open, 2, [file: 'src/esqlite3.erl', line: 59]}, {Sqlitex.Server, :init, 1, [file: 'lib/sqlitex/server.ex', line: 11]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 306]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}
    (ecto) lib/ecto/adapters/sql/worker.ex:60: Ecto.Adapters.SQL.Worker.call!/3
    (brain) lib/brain/repo.ex:2: Brain.Repo.log/2
    (ecto) lib/ecto/adapters/sql.ex:451: Ecto.Adapters.SQL.transaction/3
    (ecto) lib/ecto/repo/model.ex:183: Ecto.Repo.Model.with_transactions_if_callbacks/6
    (brain) lib/brain/cli.ex:49: Brain.CLI.process/1
    (elixir) lib/kernel/cli.ex:70: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by jazzyb** [comment]
Thanks for finding that.  I haven't run anything with escript, yet.  Just looking at the manpage for script:  "provides support for running short Erlang programs without having to compile them first".  My first instinct is that since the Erlang isn't being compiled, the shared object library is never generated.

I'll be offline most of the weekend, but I will investigate this further come Monday.

**Comment by jazzyb** [comment]
Quick update:  I am able to reproduce the error.  The escript executable cannot find the esqlite NIF because it is trying to open the shared object library relative to the esqlite build directory.  As a test, see if the issue is fixed when you create a link to the directory of the esqlite `priv/` folder:

```
$ ln -s deps/esqlite/priv/ priv
```

(The above command assumes you are on a *nix system.)

Now, the escript executable should run in your build directory.  However, if you cd to another directory without the above `priv/` folder, you should see the error return.

This could be a known issue with respect to NIFs and escript, or there may be some sort of configuration which is necessary in esqlite to package the shared object library.

I’ll leave the bug label on this issue until I have figured out a work-around.

**Comment by norbu09** [comment]
Tried to link `esqlite3_nif.so` to the `priv` directory local to the escript but did not work either. I am sure this issue did come up for others using NIFs in escripts. I'll do more playing around and see if I bump into more issues and will raise them here. Nothing urgent from my end though, just thought I'll see if I can help in some way.

**Comment by jazzyb** [comment]
Just curious:  What's your `iex --version` output?

**Comment by norbu09** [comment]
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10]
[hipe] [kernel-poll:false] [dtrace]

Elixir 1.0.4

On Mon, May 25, 2015 at 08:12:43AM -0700, Jason M Barnes wrote:

> Just curious:  What's your `iex --version` output?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jazzyb/sqlite_ecto/issues/23#issuecomment-105249658

## 

Lenz Gschwendtner - startup punk
co-founder iwantmyname.com
PGP: 3133 DDED 2DB2 E61C 7EC8  15C7 32C6 6B3B FDD0 D423
https://keybase.io/norbu09

**Comment by jazzyb** [comment]
Via Jose Valim:  "escripts do not work when they need to read values from priv"  :(

See:  https://groups.google.com/d/msgid/elixir-lang-talk/CAGnRm4%2B7Tfrh7YxNv_8101b1z9N%3DrkksHm4F52qTNvb0SBswQQ%40mail.gmail.com?utm_medium=email&utm_source=footer

**Comment by baroldgene** [comment]
For someone stumbling across this in the future, this fixed the issue for me:
`cp deps/esqlite/priv/esqlite3_nif.so ./priv/`
Didn't try the symlinking, but this seemed to work.  

I imagine this makes the escript entirely non-portable though.  :-(
