### ISSUE TITLE
Getting error in the tutorial example.

### ISSUE THREAD

**Issue by xpqz** [jazzyb/sqlite_ecto#33]
Working through the tutorial in the wiki (https://github.com/jazzyb/sqlite_ecto/wiki/Basic-Sqlite.Ecto-Tutorial) I'm getting the following error when running `mix ecto.migrate`:

`
** (MatchError) no match of right hand side value: %{num_rows: 1, rows: [{0}]}
    lib/sqlite_ecto.ex:31: Sqlite.Ecto.ddl_exists?/3
    (ecto) lib/ecto/migration/schema_migration.ex:20: Ecto.Migration.SchemaMigration.ensure_schema_migrations_table!/1
    (ecto) lib/ecto/migrator.ex:36: Ecto.Migrator.migrated_versions/1
    (ecto) lib/ecto/migrator.ex:134: Ecto.Migrator.run/4
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2`

Elixir 1.0.4

**Comment by jazzyb** [comment]
Sorry about that.  There have been a lot of API changes to Ecto in the run up to 1.0, and I haven't kept the tutorial up to date.  I will fix.

**Comment by jazzyb** [comment]
I have updated the tutorial.  Thanks for the notice that it was out of date.  By the way, based on your error message, it looks like the version of Sqlite.Ecto that you were using is incompatible with the version of Ecto that you were using.  The current mapping is like so:

| Sqlite.Ecto | Ecto |
| :-: | :-: |
| 0.1.0 | 0.11.0+ |
| 0.2.0 | 0.12.1+ |
| 0.3.0 | 0.13.1+ |
| 0.4.1 | 0.14.0+ |

Note that due to bugs in Ecto, Sqlite.Ecto is incompatible with versions 0.13.0 and 0.12.0 of Ecto.  I intend to sync the major and minor versions of Sqlite.Ecto to Ecto once Ecto 1.0 is released to avoid any confusion in the future.

Thanks again!
