### ISSUE TITLE
Add a note about unique_constraint on unique constraint errors

### ISSUE THREAD

**Issue by josevalim** [jazzyb/sqlite_ecto#37]
Today, users trying to sqlite_ecto with unique constraint are confused why it does not work. For example:

https://gist.github.com/anonymous/303ca57687ca41a5272a

Maybe we should add a note of sorts: "(note use of unique_constraint/3 is not supported on sqlite_ecto. It will always raise this error message)". Thoughts?

**Comment by jazzyb** [comment]
Thanks for filing this bug!

First, I should definitely add a note to the [README](https://github.com/jazzyb/sqlite_ecto#ignored-ecto-constraints) about this.  I have a section perfect for such constraints, but I neglected to point them out.

Second, I think the best way to handle this is to log warnings whenever `to_constraint/1` is called -- similar to the one you have above.  Can I somehow use the Ecto logger to display this warning, or will I need to add my own logging?  (I ask because I've never touched logging in Elixir.)  Other than the warning, I will not change the default return value of `[]`.

Third, I vaguely remember that in addition to unique constraints, SQLite also had a problem identifying foreign key constraints.  Are there any other Ecto constraints that I am forgetting?

**Comment by josevalim** [comment]
> First, I should definitely add a note to the README about this. I have a section perfect for such constraints, but I neglected to point them out.

Agreed.

> Second, I think the best way to handle this is to log warnings whenever to_constraint/1 is called

We will then emit warnings all the time because we always call it. :( Btw, logging with Elixir is very easy:

``` elixir
require Logger
Logger.warn "oops"
```

And that is it.

> Third, I vaguely remember that in addition to unique constraints, SQLite also had a problem identifying foreign key constraints. Are there any other Ecto constraints that I am forgetting?

Those are two so far.

**Comment by jazzyb** [comment]
> We will then emit warnings all the time because we always call it. :(

Hmm.  Well, I'll try to look for a place to put the warning that won't be that annoying -- maybe catch the error, warn, then reraise?  I just feel like a detailed warning somewhere before the error is raised is more likely to be seen and understood by developers than any amount of detail in the README/docs.

I'm on a business trip at the moment, but I'll try to find time to get the code and docs fixed up in the next day or two.

Thanks again!

**Comment by josevalim** [comment]
> I'm on a business trip at the moment, but I'll try to find time to get the code and docs fixed up in the next day or two.

There is no pressure on this. Enjoy the trip! :)
